# Generated by Django 3.1.7 on 2021-08-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('customer', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30, null=True)),
                ('merchant', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('amount', models.FloatField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
