# Generated by Django 3.1.7 on 2021-08-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='classification',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
