# Generated by Django 3.1.7 on 2021-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20210812_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='step',
        ),
        migrations.AlterField(
            model_name='predresults',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=30, null=True),
        ),
    ]
