# Generated by Django 3.1.7 on 2021-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20210814_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30, null=True),
        ),
    ]
