# Generated by Django 3.1.7 on 2021-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20210814_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='predresults',
            name='age',
            field=models.CharField(choices=[('0', '<= 18'), ('1', '19-25'), ('2', '26-35'), ('3', '36-45'), ('4', '46-55'), ('5', '56-65'), ('6', '>65'), ('U', 'unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='category',
            field=models.CharField(choices=[('es_barsandrestaurants', 'es_barsandrestaurants'), ('es_contents', 'es_contents'), ('es_fashion', 'es_fashion'), ('es_food', 'es_food'), ('es_health', 'es_health'), ('es_home', 'es_home'), ('es_hotelservices', 'es_hotelservices'), ('es_hyper', 'es_hyper'), ('es_leisure', 'es_leisure'), ('es_otherservices', 'es_otherservices'), ('es_sportsandtoys', 'es_sportsandtoys'), ('es_tech', 'es_tech'), ('es_transportation', 'es_transportation'), ('es_travel', 'es_travel'), ('es_wellnessandbeauty', 'es_wellnessandbeauty')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='gender',
            field=models.CharField(choices=[('E', 'E'), ('F', 'F'), ('M', 'M'), ('U', 'U')], max_length=30, null=True),
        ),
    ]
